### ISSUE TITLE
Comprehensive review

### ISSUE THREAD

**Issue by phobson** [Geosyntec/python-tidegates#13]
See also: https://github.com/Geosyntec/python-tidegates/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.1

The general codebase needs a peer review. To me, that means:

 - [ ] confirm that the test suite passes on someone else computer besides the one I'm using
 - [ ] review the tests and confirm that they are sufficiently stringent on their functions
 - [ ] review inline documentation to confirm that it's accurate
 - [ ] confirm that the overall goals of the tool are met.

The last point makes you wonder: What are the overall goes of the tool?

Well, they are (so far):
  - [ ] The user should be able to open up the toolbox in ArcMap or ArcCatalog >= 10.2
  - [ ] The toolbox should allow the user to select a DEM, polygon layer, ID column, a flood elevation, an output filename, and layers whose impact due to flooding will be assessed
  - [ ] The tool should then determine which portions of the polygons are flooded based on the flood elevation parameter, return those new polygons

Remaining items to be implemented:
  - [ ] [Flood scenarios evaluated](#6) in the last item above should also be used to assess the damage in terms of:
    1. Total area (in acres) flooded
    1. Total area (in acres) of wetlands flooded
    1. Number of flooded buildings
    1. An output layer showing all of the flooded buildings
  See #6 for more info
  - [ ] The toolbox should also be able to process multiple elevations at once, saving the output in a single layer. See #5.
  - [ ] An additional toolbox should be made to automatically run all the "standard" scenarios. See #4.

**Comment by HEdingfield** [comment]
See: https://github.com/phobson/python-tidegates/pull/1
